version: "3.9"

services:
  llm-api:
    build: .
    container_name: doc_reader_llm
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${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}
    volumes:
      - ./data:/app/data
